"""add name column to cocktails

Revision ID: ee0ab629ca0f
Revises: 9225055cba58
Create Date: 2025-06-05 12:07:46.557278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0ab629ca0f'
down_revision = '9225055cba58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktails', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
